# Generated by Django 6.0.1 on 2026-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type1', models.CharField(max_length=30)),
                ('type2', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('hp', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
